import fs from 'node:fs/promises';
const file=process.argv[2]||'docs/signal.json',raw=await fs.readFile(file,'utf8');let s;try{s=JSON.parse(raw);}catch{throw new Error('signal.json is not valid JSON');}
const fail=[],finite=n=>Number.isFinite(Number(n));
if(!Number.isInteger(s.schemaVersion)||s.schemaVersion<28)fail.push('schemaVersion');if(s.source!=='Teststock')fail.push('source');
const generated=new Date(s.generatedAt).getTime(),age=Date.now()-generated;if(!Number.isFinite(generated)||age< -5*60_000||age>10*60_000)fail.push('generatedAt freshness');
if(s.funding?.agentMayInitiateDeposits!==false||s.funding?.agentMayInitiateBankTransfers!==false)fail.push('funding lock');
const tiers=s.capitalLadder?.tiers;if(!Array.isArray(tiers)||tiers.length<5)fail.push('capital tiers');else{let last=-Infinity;for(const t of tiers){if(!finite(t.minEquity)||Number(t.minEquity)<last)fail.push('tier ordering');last=Number(t.minEquity);}if(tiers.find(t=>Number(t.minEquity)===100)?.label!=='PROVE')fail.push('$100 PROVE boundary');}
for(const plan of [s.stockPlan,s.cryptoPlan])if(!plan||typeof plan!=='object')fail.push('asset plan missing');
for(const order of s.stockPlan?.stockOrders||[]){for(const k of ['minimumEntry','maximumEntry','stop','target1','target2'])if(!finite(order[k])||Number(order[k])<=0)fail.push(`stock ${k}`);if(Number(order.maximumEntry)<Number(order.minimumEntry))fail.push('stock entry range');if(Number(order.rewardRisk||0)>0&&Number(order.rewardRisk)<2.5)fail.push('stock target2 reward-risk gate');if(![0,25].includes(Number(order.exitPlan?.target1SellPctOfOriginal)))fail.push('stock target1 scale-out');if(Number(order.exitPlan?.maxRunnerPctOfOriginal||0)>25)fail.push('stock runner too large');if(Number(order.exitPlan?.runnerPctOfOriginal||0)>Number(order.exitPlan?.maxRunnerPctOfOriginal||0))fail.push('stock runner exceeds validated max');if(order.protectionPlan?.policyRef!=='signal.fractionalProtectionPolicy')fail.push('stock fractional protection plan');if(order.operationalSafety?.wholeShareProtectabilityIsTieBreakerOnly!==true)fail.push('stock whole-share tie-breaker metadata');if(order.operationalSafety?.eventDrivenExecutionDispatchRef!=='signal.eventDrivenExecutionDispatch')fail.push('stock execution-dispatch metadata');}
const candidateQueue=s.stockPlan?.stockCandidateQueue||[];
if(candidateQueue.length>15)fail.push('stock candidate queue too large');
if(new Set(candidateQueue.map(x=>x.ticker)).size!==candidateQueue.length)fail.push('duplicate stock candidate queue ticker');
for(let i=0;i<candidateQueue.length;i++){const x=candidateQueue[i];if(Number(x.queueRank)!==i+1)fail.push('stock candidate queue rank');for(const k of ['minimumEntry','maximumEntry','stop','target1','target2'])if(!finite(x[k])||Number(x[k])<=0)fail.push(`stock candidate ${k}`);if(!['PRIMARY','RESERVE'].includes(x.queueRole))fail.push('stock candidate queue role');}
for(const order of s.cryptoPlan?.cryptoOrders||[]){for(const k of ['minimumEntry','maximumEntry','stop','target1','target2'])if(!finite(order[k])||Number(order[k])<=0)fail.push(`crypto ${k}`);}
if(s.systemHealth?.actionOnCriticalFailure!=='NO_NEW_TRADES_MANAGE_EXITS_IF_POSSIBLE')fail.push('system health fail-closed policy');
if(!s.entryGateRobustness?.secondHoldoutStart||!s.entryGateRobustness?.secondHoldout)fail.push('second untouched holdout');
if(!s.entryGateRobustness?.regimeEntryProfiles)fail.push('regime entry profiles');
if(Number(s.tradeFrequencyGuard?.maxNewPositionsPerSevenDays||0)<7)fail.push('multi-position weekly capacity');
if(Number(s.tradeFrequencyGuard?.maxNewPositionsPerDay||0)>4)fail.push('daily position cap too high');
if(Number(s.portfolioGuard?.maxConcurrentTeststockPositions||0)>4)fail.push('concurrent portfolio cap too high');
if(Number(s.executionQuality?.maxStockSpreadPct||99)>.35)fail.push('stock spread cap');
if(!s.executionQuality?.gapRiskGuard?.enabled)fail.push('gap-risk guard');
if(!s.executionQuality?.liquidityRanking?.enabled)fail.push('liquidity ranking');
if(!s.symbolProbationPolicy?.enabled)fail.push('symbol probation');
if(!s.probabilityFirstPolicy||s.probabilityFirstPolicy.status==='UNAVAILABLE')fail.push('probability-first policy');
if(Number(s.probabilityFirstPolicy?.stocks?.minHistoricalSamples||0)<20)fail.push('probability stock sample floor');
if(Number(s.probabilityFirstPolicy?.stocks?.minCostAdjustedConservativeExpectedR||0)<.5)fail.push('cost-adjusted stock expectancy floor');
if(s.probabilityFirstPolicy?.stocks?.rewardRiskQualificationTarget!=='TARGET2')fail.push('target2 reward-risk qualification');
if(Number(s.probabilityFirstPolicy?.crypto?.liveEvidenceMinimumResolvedTrades||0)<5)fail.push('crypto real-fill evidence floor');
const seed=s.probabilityFirstPolicy?.crypto?.dayTradeSeedLane;if(seed?.enabled!==true||Number(seed?.maxOrderUsd)!==5||Number(seed?.maxConcurrentPositions)!==1||Number(seed?.maxHoldingHours)!==8||Number(seed?.maxStopLossesPerUtcDay)!==2||seed?.requiresBrokerResidentStop!==true)fail.push('crypto seed lane bounds');
const cryptoDay=s.probabilityFirstPolicy?.crypto?.dayTradeEntry;if(Number(cryptoDay?.minimumRsi)!==50||Number(cryptoDay?.maximumRsi)!==70||cryptoDay?.requiresPullbackToSupportOrVwap!==true||cryptoDay?.requiresMomentumTurnUp!==true||cryptoDay?.requiresVolumeConfirmation!==true||Number(cryptoDay?.minimumRewardRisk)<3)fail.push('crypto day-trade entry policy');
if(s.shadowEvidencePolicy?.automaticLooseningAllowed!==false)fail.push('shadow automatic loosening lock');
if(s.executionTelemetryPolicy?.sourceOfTruth!=='ROBINHOOD_CONFIRMED_FILLS_AND_ORDERS')fail.push('execution telemetry source');if(!s.dailySummaryPolicy?.enabled)fail.push('daily summary policy');
if(s.runnerContinuationPolicy?.enabled!==true)fail.push('runner policy');
if(Number(s.runnerContinuationPolicy?.maximumRunnerPctOfOriginal||0)>25)fail.push('runner max allocation');
if(Number(s.runnerContinuationPolicy?.moderateRunnerPctOfOriginal||0)>Number(s.runnerContinuationPolicy?.maximumRunnerPctOfOriginal||0))fail.push('runner moderate allocation');
if(Number(s.runnerContinuationPolicy?.noSignalRunnerPctOfOriginal)!==0)fail.push('runner fail-closed allocation');
if(s.runnerContinuationPolicy?.otherwise?.action!=='EXIT_REMAINDER_AT_OR_AFTER_TARGET2')fail.push('runner weak-signal exit');
if(!s.exitPolicyValidation?.recommendedPolicy)fail.push('exit-policy validation');
if(s.exitPolicyValidation?.automaticRiskIncreaseAllowed!==false)fail.push('exit-policy risk lock');
if(s.fractionalProtectionPolicy?.enabled!==true)fail.push('fractional protection policy');
if(s.fractionalProtectionPolicy?.observedPlatformConstraint?.fractionalTriggeredSellOrdersSupported!==false)fail.push('fractional trigger limitation');
if(Number(s.fractionalProtectionPolicy?.fractionalSyntheticStop?.maximumPlannedStopRiskPctOfLiveEquity)!==0.75)fail.push('fractional synthetic risk cap');
if(Number(s.fractionalProtectionPolicy?.fractionalSyntheticStop?.maximumMonitoringIntervalMinutesDuringRegularSession)!==5)fail.push('fractional monitoring interval');
if(s.fractionalProtectionPolicy?.fractionalSyntheticStop?.requiresActiveMonitoring!==true)fail.push('fractional active monitoring requirement');
if(s.fractionalProtectionPolicy?.preferredArchitecture!=='WHOLE_SHARE_TIE_BREAKER_WHEN_GENUINELY_COMPARABLE')fail.push('whole-share tie-breaker architecture');
if(s.fractionalProtectionPolicy?.wholeShareTieBreaker?.enabled!==true)fail.push('whole-share tie-breaker policy');
if(s.fractionalProtectionPolicy?.wholeShareTieBreaker?.qualityMayNotBeSacrificed!==true)fail.push('whole-share quality precedence');
if(s.smallAccountAccessPolicy?.fractionalSharesAllowed!==true||s.smallAccountAccessPolicy?.wholeShareIsTieBreakerOnly!==true)fail.push('small-account fractional access policy');
if(Number(s.smallAccountAccessPolicy?.tieDefinition?.maxPortfolioOpportunityScoreDifference||99)>3)fail.push('whole-share tie score tolerance');
if(Number(s.smallAccountAccessPolicy?.tieDefinition?.maxCostAdjustedConservativeExpectedRDifference||99)>.10)fail.push('whole-share expectancy tie tolerance');
if(s.systemHealth?.runtimeFractionalProtection?.requiredForNewFractionalStock!==true)fail.push('fractional runtime health requirement');
if(s.nonLlmTriggerMonitor?.enabled!==true||s.nonLlmTriggerMonitor?.claudeContinuousMarketPollingRequired!==false)fail.push('non-LLM trigger monitor');
if(Number(s.nonLlmTriggerMonitor?.monitorCadenceMinutes||99)>5)fail.push('trigger monitor cadence');
if(s.eventDrivenExecutionDispatch?.enabled!==true)fail.push('event-driven execution dispatch');
if(s.eventDrivenExecutionDispatch?.claudeShouldPollMarket!==false)fail.push('Claude market polling lock');
if(s.eventDrivenExecutionDispatch?.noActionBehavior!=='STOP_BEFORE_ROBINHOOD_OR_FULL_SIGNAL')fail.push('low-credit idle behavior');
if(s.eventDrivenExecutionDispatch?.priorityOrder?.[0]!=='TRIGGER_1_STOP')fail.push('stop dispatch priority');
if(s.eventDrivenExecutionDispatch?.stopPriority!==true)fail.push('stop priority lock');
if(!String(s.eventDrivenExecutionDispatch?.dispatchUrl||'').includes('execution-dispatch.json'))fail.push('dispatch URL');
if(s.systemHealth?.executionDispatch?.requiredForLowCreditExecution!==true)fail.push('dispatch health dependency');
if(!s.portfolioCorrelationIntelligence||s.portfolioCorrelationIntelligence.status==='UNAVAILABLE_FAIL_CLOSED')fail.push('portfolio correlation intelligence');
if(Number(s.portfolioCorrelationIntelligence?.highCorrelationThreshold||0)!==0.75)fail.push('correlation threshold');
if(Number(s.portfolioCorrelationIntelligence?.policy?.maxNamesPerHighCorrelationCluster||0)>2)fail.push('correlation cluster cap');
if(s.portfolioCorrelationIntelligence?.policy?.thirdNameAllowed!==false)fail.push('third correlated name block');
if(!s.championChallenger?.champion?.exitPolicy)fail.push('champion challenger');
if(s.championChallenger?.promotionPolicy?.entryRiskIncreaseAllowed!==false)fail.push('challenger risk lock');
if(s.executionLearningPolicy?.sourceOfTruth!=='ROBINHOOD_CONFIRMED_FILLS_ONLY')fail.push('execution learning source');
if(s.executionLearningPolicy?.mayIncreaseSize!==false)fail.push('execution learning size lock');
if(s.postTradeAttributionPolicy?.enabled!==true)fail.push('post-trade attribution');
if(s.setupSpecificExitResearch?.automaticLivePromotionAllowed!==false)fail.push('setup exit promotion lock');
if(s.dataFreshness?.status!=='GENERATED_THIS_RUN')fail.push('data freshness status');
const lastSuccess=new Date(s.dataFreshness?.lastSuccessfulGeneration||0).getTime();if(!Number.isFinite(lastSuccess)||Math.abs(Date.now()-lastSuccess)>10*60_000)fail.push('last successful generation freshness');
if(Number(s.dataFreshness?.expectedRefreshCadenceMinutes||0)!==10)fail.push('refresh cadence metadata');
if(s.dataFreshness?.failClosed!==true)fail.push('freshness fail-closed');
if(Number(s.dataFreshness?.cryptoAgeMinutes??999)>25)fail.push('crypto data stale at generation');
if(Number(s.dataFreshness?.entryGateValidationAgeMinutes??999)>120)fail.push('entry-gate validation stale');
if(!s.generatorIntegrity?.lastKnownGoodFallback)fail.push('last-known-good fallback metadata');
for(const k of ['dualUntouchedHoldouts','regimeSpecificEntryProfiles','setupClusterAndSymbolRealFillLearning','staleDataFailClosed','costAdjustedExpectancy','target2RewardRiskQualification','conditionalRunnerExit','fractionalSyntheticProtection','exitPolicyHoldoutValidation','portfolioCorrelationIntelligence','championChallengerGovernance','executionLearning','postTradeAttribution','setupSpecificExitResearch','wholeShareTieBreaker','smallAccountAccessPolicy','nonLlmTriggerMonitor','lowCreditTriggerExecution','eventDrivenExecutionDispatch'])if(s.generatorIntegrity?.traceableFeatures?.[k]!==true)fail.push(`integrity feature ${k}`);
if(fail.length)throw new Error(`signal validation failed: ${[...new Set(fail)].join(', ')}`);console.log(`signal validation passed: schema v${s.schemaVersion}, generated ${s.generatedAt}`);
